# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMapLocationIndicator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GoogleMapLocationIndicator

  target 'GoogleMapLocationIndicator-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoogleMapLocationIndicatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GoogleMapLocationIndicator-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GoogleMapLocationIndicator-tvOS

  target 'GoogleMapLocationIndicator-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
